import ChevronHeader from "./materials/ChevronHeader";

import "../styles/TermsOfUse.scss";

import { useContext } from 'react';
import TranslationContext from '../context/TranslationContext';

export default function TermsOfUse({ modal }) {
  const { enFr, term } = useContext(TranslationContext);
  window.scrollTo(0,0); // ensure page is scrolled to top upon mount

  return (
    <main className={`nav-shadow ${modal ? "blur" : ""}`}>
      <ChevronHeader
        bgLeft={'bg-header-orange'}
        text={enFr(
                <>Terms of Use</>,
                <span className="uppercase">Conditions D’utilisation</span>,
              )}
        bgRight={'bg-header-red'}
      />
      <article className="terms">
        <h2 className="font-orange font-bold uppercase">
          {enFr(
            <>Terms of Service</>,
            <>Conditions D’utilisation</>
          )}
        </h2>
        <p>
          {enFr(
            <>
              Last Updated: April 29, 2019<br/>
              <br/>
              Please read these Terms of Service (the “<span className="underline">Agreement</span>”) carefully. By clicking or tapping “OK” or “Agree” (or a similar term) in connection with this Agreement, or by using the Services (as defined below), you agree to this Agreement. We recommend that you print a copy of this Agreement for future reference. We retain the right to make changes, as outlined below.<br/>
              <br/>
              This Agreement is between you and Janssen Inc. (“<span className="underline">Company</span>” or “<span className="underline">we</span>” or “<span className="underline">us</span>” or “<span className="underline">our</span>”) concerning your use of the Dosing Conversion Guides site located at invegasustennahcp.ca (the “<span className="underline">Site</span>”) the mobile software application in connection with which you are accessing this Agreement (the “<span className="underline">App</span>” or the “<span className="underline">Services</span>”).<br/>
              <br/>
              If you are not willing to accept the terms and conditions in the Agreement, we ask that you not access or use the Services or post or submit any materials on it or order any items from it. Please review our Privacy Policy located at <a href="http://www.janssen.com/canada/privacy" target="_blank" rel="noreferrer" aria-label="Privacy Policy">http://www.janssen.com/canada/privacy</a> for details about what information we collect and how we use it.<br/>
              <br/>
              THIS SITE IS INTENDED FOR AND DIRECTED TO RESIDENTS OF CANADA. YOU AFFIRM THAT YOU ARE OF LEGAL AGE TO ENTER INTO THIS AGREEMENT.<br/>
              <br/>
              IF YOU ARE USING THE SERVICES ON BEHALF OF, OR FOR THE BENEFIT OF, ANY ORGANIZATION WITH WHICH YOU ARE ASSOCIATED, THEN YOU AGREE TO THE TERMS OF THIS AGREEMENT ON BEHALF OF YOURSELF AND SUCH ORGANIZATION, AND YOU CONFIRM THAT YOU HAVE THE LEGAL AUTHORITY TO BIND SUCH ORGANIZATION TO THIS AGREEMENT.
              References to “you” and “your” in this Agreement will refer to both you and any such organization.<br/>
              <br/>
              <strong className="font-bold">1. Our Right to Make Changes.</strong> We may change this Agreement from time to time (for any reason, such as changes in the functions or services offered by this Site or to reflect a change in the law) by notifying you of such changes by any reasonable means and by making available a revised Agreement through the Services. Any such changes will not apply to any dispute between you and us arising prior to the date on which we posted the revised Agreement incorporating such changes or otherwise notified you of such changes. Your clicking or tapping “OK” or “Agree” (or a similar term) in connection with this Agreement or your use of the Services following any changes will constitute your acceptance of such changes. The “Last Updated” legend above indicates when this Agreement was last changed.<br/>
              To the extent permitted by applicable law, we may, at any time and without liability, modify or discontinue all or part of the Services (e.g., to reflect changes in the relevant laws, to protect the security of the Services or to implement reasonable technical adjustments and improvements, to modify the services and functions provided by the Site); charge, modify or waive any fees required to use the Services where reasonably necessary; or offer opportunities to some or all users, at our sole discretion. We will seek to notify you by reasonable means of (i) any modifications that will have a material adverse effect on your use of the Services, taken as a whole; and (ii) any material increase in the fees charged by us to use the Services.<br/>
              <br/>
              <strong className="font-bold">2. Information Disclaimer.</strong> THE INFORMATION INCLUDING ANY, ADVICE AND RECOMMENDATIONS PROVIDED AS PART OF THE SERVICES IS INTENDED SOLELY FOR EDUCATIONAL AND INFORMATIONAL PURPOSES. IT IS NOT INTENDED AS MEDICAL OR HEALTHCARE ADVICE, OR TO BE USED FOR MEDICAL DIAGNOSIS OR TREATMENT, FOR ANY INDIVIDUAL PROBLEM. IT IS ALSO NOT INTENDED AS A SUBSTITUTE FOR PROFESSIONAL ADVICE AND SERVICES FROM A QUALIFIED HEALTHCARE PROVIDER FAMILIAR WITH YOUR UNIQUE FACTS. ALWAYS SEEK THE ADVICE OF YOUR DOCTOR OR OTHER QUALIFIED HEALTHCARE PROVIDER REGARDING ANY MEDICAL CONDITION AND BEFORE STARTING ANY NEW TREATMENT. YOUR USE OF THE SERVICES IS SUBJECT TO THE ADDITIONAL DISCLAIMERS AND CAVEATS THAT MAY APPEAR THROUGHOUT THE SERVICES.<br/>
              <br/>
              WE ASSUME NO RESPONSIBILITY FOR ANY CONSEQUENCE RELATING DIRECTLY OR INDIRECTLY TO ANY ACTION OR INACTION YOU TAKE BASED ON THE INFORMATION, OR OTHER MATERIAL PROVIDED AS PART OF THE SERVICES. WHILE WE STRIVE TO KEEP THE INFORMATION PROVIDED BY THE SERVICES TO BE ACCURATE, COMPLETE, AND UP TO DATE, WE DO NOT GIVE ANY ASSURANCES AND WILL NOT BE RESPONSIBLE FOR ANY DAMAGE OR LOSS RELATED TO THE ACCURACY, COMPLETENESS, OR TIMELINESS OF THE INFORMATION PROVIDED AS PART OF THE SERVICES.<br/>
              <br/>
              <strong className="font-bold">3. Information Submitted Through the Services.</strong> Your submission of information through the Services is governed by our Privacy Policy.<br/>
              <br/>
              <strong className="font-bold">4. Jurisdictional Issues.</strong> The Services may not be appropriate or available for use in some jurisdictions. Any use of the Services is at your own risk, and you must comply with all applicable laws, rules and regulations in doing so. We may limit the availability of the Services at any time, in whole or in part, to any person or geographic area that we choose, in our sole discretion, for valid reasons (e.g., to comply with relevant laws and regulatory requirements, to protect the security of the Services or to implement reasonable technical adjustments).<br/>
              <br/>
              <strong className="font-bold">5. Acceptable Use and Rules of Conduct.</strong> You must not:
            </>,
            <>
              Dernière mise à jour&nbsp;: <span className="nowrap">29 avril 2019</span><br/>
              <br/>
              Veuillez lire attentivement les présentes conditions d’utilisation <span className="nowrap">(l’{term("entente")}).</span> En cliquant ou en appuyant sur <span className="nowrap">« OK »</span> ou <span className="nowrap">« J’accepte »</span> (ou un terme similaire) en lien avec la présente entente, ou en utilisant les services (tel qu’il est défini ci-dessous), vous acceptez la présente entente. Nous vous recommandons d’imprimer une copie de la présente entente afin de pouvoir la consulter ultérieurement. Nous nous réservons le droit d’y apporter des modifications, tel qu’il est indiqué ci-dessous.<br/>
              La présente entente est conclue entre vous et Janssen Inc. (la {term("société")}, {term("nous")}, {term("notre")} ou {term("nos")}) et porte sur votre utilisation du site Guides de conversion posologique à l’adresse invegasustennahcp.ca (le {term("site")}) ou de l’application logicielle mobile en lien avec laquelle vous accédez à la présente entente (l’{term("application")} ou collectivement, les {term("services")}).<br/>
              <br/>
              Si vous ne souhaitez pas accepter les conditions d’utilisation énoncées dans la présente entente, nous vous demandons de ne pas accéder aux services, utiliser les services, publier ou soumettre du matériel dans les services, ou encore commander quelque article que ce soit par l’intermédiaire des services. Veuillez consulter notre politique de confidentialité à l’adresse <a href="https://www.janssen.com/canada/fr/privacy" target="_blank" rel="noreferrer">http://www.janssen.com/canada/fr/privacy</a> pour en savoir plus sur les renseignements que nous recueillons et sur la façon dont nous les utilisons.<br/>
              <br/>
              CE SITE EST CONÇU POUR LES PERSONNES QUI RÉSIDENT AU CANADA ET S’ADRESSE À ELLES. VOUS AFFIRMEZ QUE VOUS AVEZ L’ÂGE LÉGAL POUR CONCLURE LA PRÉSENTE ENTENTE.<br/>
              <br/>
              SI VOUS UTILISEZ LES SERVICES AU NOM OU AU BÉNÉFICE DE TOUTE ORGANISATION À LAQUELLE VOUS ÊTES ASSOCIÉ, VOUS ACCEPTEZ LES CONDITIONS D’UTILISATION ÉNONCÉES DANS LA PRÉSENTE ENTENTE EN VOTRE NOM ET AU NOM DE CETTE ORGANISATION, ET VOUS CONFIRMEZ QUE VOUS ÊTES JURIDIQUEMENT AUTORISÉ À LIER CETTE ORGANISATION À LA PRÉSENTE ENTENTE. Les termes « vous » et « votre » dans la présente entente se rapportent à la fois à vous et à cette organisation.<br/>
              <br/>
              <strong className="font-bold">1. Notre droit d’apporter des modifications.</strong> Nous pouvons modifier la présente entente de temps à autre (dans quelque but que ce soit, par exemple pour modifier les fonctions ou les services offerts par ce site ou pour nous conformer à un changement législatif) en vous informant des modifications par tout moyen raisonnable et en rendant accessible une entente révisée par l’intermédiaire des services. Aucune de ces modifications ne s’appliquera à un différend entre vous et nous survenu avant la date à laquelle nous avons rendu accessible l’entente révisée comprenant les modifications ou à laquelle nous vous avons informé de ces modifications. En cliquant ou en appuyant sur « OK » ou « J’accepte » (ou un terme similaire) en lien avec la présente entente ou en utilisant les services après toute modification, vous acceptez ces modifications. La mention <span className="nowrap">« <span className="italics">Dernière mise à jour</span> »</span> ci-dessus indique la date à laquelle cette entente a été modifiée pour la dernière fois.<br/>
              <br/>
              Dans la mesure prévue par la loi applicable, nous pouvons, à tout moment et sans responsabilité, modifier ou interrompre les services intégralement ou partiellement (par exemple, pour nous conformer à des changements législatifs applicables, pour assurer la sécurité des services ou pour mettre en œuvre des ajustements et améliorations techniques raisonnables, pour modifier les services et les fonctions qu’offre le site), facturer ou modifier des frais exigés pour l’utilisation des services, ou encore y renoncer, lorsqu’il est raisonnablement nécessaire de le faire, ou offrir des occasions à certains ou à tous les utilisateurs, et ce, à notre seule discrétion. Nous tenterons de vous informer par un moyen raisonnable de i) toute modification ayant un effet négatif important sur votre utilisation des services dans leur ensemble; et ii) de toute augmentation importante des frais que nous exigeons pour l’utilisation des services.<br/>
              <br/>
              <strong className="font-bold">2. Stipulation d’exonération.</strong> LES RENSEIGNEMENTS CONTENUS DANS LES SERVICES, Y COMPRIS LES AVIS ET LES RECOMMANDATIONS, SONT FOURNIS UNIQUEMENT À TITRE D’INFORMATION GÉNÉRALE. CES RENSEIGNEMENTS NE DOIVENT PAS ÊTRE CONSIDÉRÉS COMME DES CONSEILS MÉDICAUX OU DE SANTÉ, NI ÊTRE UTILISÉS À DES FINS DE DIAGNOSTIC OU DE TRAITEMENT MÉDICAL RELATIF À UN PROBLÈME EN PARTICULIER. ILS NE VISENT PAS À REMPLACER LES CONSEILS ET LES SERVICES D’UN PROFESSIONNEL DE LA SANTÉ QUALIFIÉ, FAMILIER AVEC VOTRE SITUATION PARTICULIÈRE. DEMANDEZ TOUJOURS L’AVIS DE VOTRE MÉDECIN OU D’UN AUTRE PROFESSIONNEL DE LA SANTÉ QUALIFIÉ LORSQU’IL S’AGIT DE VOTRE ÉTAT DE SANTÉ OU AVANT DE COMMENCER UN NOUVEAU TRAITEMENT. L’UTILISATION QUE VOUS FAITES DES SERVICES EST ASSUJETTIE AUX AVIS SUPPLÉMENTAIRES DE NON-RESPONSABILITÉ ET DE MISE EN GARDE AFFICHÉS DANS L’ENSEMBLE DES SERVICES.<br/>
              <br/>
              NOUS N’ASSUMONS AUCUNE RESPONSABILITÉ RELATIVEMENT AUX CONSÉQUENCES LIÉES DIRECTEMENT OU INDIRECTEMENT À TOUTE ACTION OU OMISSION DE VOTRE PART QUI SERAIT BASÉE SUR LES RENSEIGNEMENTS OU TOUT AUTRE MATÉRIEL FOURNI PAR L’INTERMÉDIAIRE DES SERVICES. BIEN QUE NOUS NOUS EFFORCIONS DE FOURNIR PAR L’INTERMÉDIAIRE DES SERVICES DES RENSEIGNEMENTS EXACTS, COMPLETS ET À JOUR, NOUS N’EN DONNONS AUCUNE ASSURANCE ET NOUS NE POURRONS ÊTRE TENUS RESPONSABLES RELATIVEMENT À DES PRÉJUDICES OU PERTES EN LIEN AVEC L’EXACTITUDE, L’EXHAUSTIVITÉ OU L’ACTUALITÉ DES RENSEIGNEMENTS OFFERTS PAR L’INTERMÉDIAIRE DES SERVICES.<br/>
              <br/>
              <strong className="font-bold">3. Renseignements soumis par l’intermédiaire des services.</strong> La transmission de renseignements par l’intermédiaire des services est régie par notre politique de confidentialité.<br/>
              <br/>
              <strong className="font-bold">4. Questions territoriales.</strong> Les services peuvent ne pas être appropriés ou offerts dans toutes les provinces et tous les territoires. Vous utilisez les services à vos propres risques et, ce faisant, vous devez vous conformer à l’ensemble des lois, des règlements et des règles applicables. Nous pouvons limiter la disponibilité des services à tout moment, en tout ou en partie, pour toute personne ou pour toute zone géographique, à notre seule discrétion, pour des raisons valables (par exemple, pour nous conformer aux lois et aux exigences réglementaires applicables, pour assurer la sécurité des services ou mettre en œuvre des ajustements techniques raisonnables).<br/>
              <br/>
              <strong className="font-bold">5. Utilisation acceptable et règles de conduite.</strong> Il est interdit&nbsp;:
            </>,
          )}
        </p>
        <ul className="terms-bullet-list">
          {enFr(
            <>
              <li><span>Post, transmit or otherwise make available through or in connection with the Services any materials that are or may be: (a) threatening, harassing, degrading, hateful, intimidating, or otherwise fail to respect the rights and dignity of others; (b) defamatory, libelous or fraudulent; (c) obscene, indecent, pornographic or otherwise objectionable; or (d) protected by copyright, trademark, trade secret, right of publicity or privacy or any other proprietary right, without the express prior written consent of the applicable owner.</span></li>
              <li><span>Post, transmit or otherwise make available through or in connection with the Services any virus, worm, Trojan horse, Easter egg, time bomb, spyware or other computer code, file or program that is or is potentially harmful or invasive or intended to damage or hijack the operation of, or to monitor the use of, any hardware, software or equipment (each, a “Virus”).</span></li>
              <li><span>Use the Services for any commercial purpose, including use for your commercial purposes or any commercial purposes that will benefit you in any way.</span></li>
              <li><span>Use the Services for any purpose that is fraudulent or otherwise unlawful.</span></li>
              <li><span>Collect information about users of the Services in any way, including through reverse engineering.</span></li>
              <li><span>Interfere with the operation of the Services or the servers or networks used to make the Services available, including by hacking or defacing any portion of the Services, or violate any requirement or policy of such servers or networks.</span></li>
              <li><span>Restrict or inhibit any other person from using the Services.</span></li>
              <li><span>Reproduce, modify, adapt, translate, create derivative works of, sell, rent, lease, loan, timeshare, distribute or otherwise exploit any portion of (or any use of) the Services except as expressly authorized under this Agreement, without our express prior written consent.</span></li>
              <li><span>Reverse engineer, decompile or disassemble any portion of the Services, except where such restriction is expressly prohibited by applicable law.</span></li>
              <li><span>Remove any copyright, trademark or other proprietary rights notice from the Services.</span></li>
              <li><span>Incorporate any portion of the Services into any product or service, without our express prior written consent.</span></li>
              <li><span>Systematically download and store Services content.</span></li>
              <li><span>Use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or otherwise gather Services content, or reproduce or circumvent the navigational structure or presentation of the Services, without our express prior written consent. Notwithstanding the foregoing, and subject to compliance with any instructions posted in the robots.txt file located in the root directory of the Services, we grant to the operators of public search engines permission to use spiders to copy materials from the Services for the sole purpose of (and solely to the extent necessary for) creating publicly available, searchable indices of such materials, but not caches or archives of such materials. We reserve the right to revoke such permission either generally or in specific cases, at any time and without notice. </span></li>
            </>,
            <>
              <li><span>de publier, de transmettre ou de rendre autrement accessible par l’intermédiaire des services ou en lien avec ceux-ci tout matériel qui est ou pourrait être : a) menaçant, malveillant, humiliant, dégradant, haineux, intimidant ou constituant une atteinte aux droits et à la dignité d’autrui; b) diffamatoire, calomnieux ou frauduleux; c) obscène, indécent, pornographique ou autrement répréhensible; ou d) protégé par des lois sur le droit d’auteur, les marques de commerce, le secret commercial, le droit à l’image ou à la vie privée ou tout autre droit de propriété, sans avoir obtenu au préalable et par écrit le consentement exprès du propriétaire concerné;</span></li>
              <li><span>de publier, de transmettre ou de rendre autrement accessible par l’intermédiaire des services ou en lien avec ceux-ci tout virus, ver, cheval de Troie, œuf de Pâques, bombe à retardement, logiciel espion ou autre code, fichier ou programme informatique qui est ou pourrait être nuisible ou invasif, ou vise à endommager, détourner ou surveiller le fonctionnement de tout matériel, logiciel ou équipement (chacun, un {term("virus")});</span></li>
              <li><span>d’utiliser les services à des fins commerciales, y compris à des fins commerciales dans votre intérêt ou à des fins commerciales qui vous seront bénéfiques de quelque manière que ce soit;</span></li>
              <li><span>d’utiliser les services à des fins frauduleuses ou autrement illégales;</span></li>
              <li><span>de recueillir des renseignements sur les utilisateurs des services de quelque manière que ce soit, y compris par une analyse à rebours;</span></li>
              <li><span>de nuire au fonctionnement des services ou des serveurs ou des réseaux utilisés pour rendre les services accessibles, y compris par le piratage ou la défiguration de toute partie des services ou la violation de toute exigence ou politique se rapportant à ces serveurs ou à ces réseaux;</span></li>
              <li><span>de restreindre ou d’entraver l’utilisation des services de toute autre personne;</span></li>
              <li><span>de reproduire, de modifier, d’adapter, de traduire, de vendre, de louer, de prêter, de partager, de distribuer ou d’exploiter autrement toute partie (ou toute utilisation) des services et de créer des œuvres dérivées de celle-ci, sauf tel qu’il est expressément autorisé de le faire en vertu de la présente entente, sans notre consentement exprès par écrit et au préalable;</span></li>
              <li><span>d’effectuer une analyse à rebours, décompiler ou désassembler toute partie des services, sauf si cette restriction est expressément interdite par une loi applicable;</span></li>
              <li><span>de supprimer toute mention de droits d’auteur, de marque de commerce ou d’autres droits de propriété des services;</span></li>
              <li><span>d’intégrer toute partie des services à un produit ou à un service, sans notre consentement exprès par écrit et au préalable;</span></li>
              <li><span>de télécharger et stocker systématiquement le contenu des services;</span></li>
              <li><span>d’utiliser un robot, une araignée, une application de recherche ou d’extraction ou tout autre dispositif manuel ou automatique pour extraire, indexer, explorer ou obtenir autrement les données des services, ou de reproduire ou contourner la structure de navigation ou la présentation des services, sans notre consentement exprès par écrit et au préalable; Nonobstant ce qui précède et sous réserve du respect de toute instruction affichée dans le fichier robots.txt situé dans le répertoire racine des services, nous accordons aux exploitants de moteurs de recherche publics l’autorisation d’utiliser des araignées pour copier du matériel des services à la seule fin (et uniquement dans la mesure nécessaire) de créer des indices de ce matériel accessibles au public par requête, et non pas de créer des caches ou des archives de ce matériel. Nous nous réservons le droit de révoquer cette autorisation, en général ou dans des cas particuliers, à tout moment et sans préavis.</span></li>        
            </>,
          )}
        </ul>
        <p>
          {enFr(
            <>
              You are responsible for obtaining, maintaining and paying for all hardware, telecommunications and other services needed for you to use the Services.<br/>
              <br/>
              <strong className="font-bold">6. Electronic Communications.</strong>The information communicated as part of the Services may constitute an electronic communication. When you communicate with us through the Services or via other forms of electronic media, such as email, you are communicating with us electronically. You agree that we may communicate electronically, subject to local privacy and Anti-Spam laws, and that such communications, as well as notices, disclosures, agreements, and other communications that we provide to you electronically, are equivalent to communications in writing and shall have the same force and effect as if they were in writing and signed by the party sending the communication.<br/>
              <br/>
              <strong className="font-bold">7. Registration.</strong> You may need to register to use the Services. We may reject, or require that you change, any user name, password or other information that you provide. Your user name and password are for your personal use only. You are solely responsible for maintaining the confidentiality of your credentials and for restricting access to your mobile device, computer, and/or other means of accessing the Services. We are not responsible for any use of your credentials caused by your failure to keep them confidential. You are solely responsible for all activities that occur under your account, either with or without your knowledge. You must promptly notify us of any unauthorized use of your credentials or account of which you become aware. We recommend that, to the extent you access the Services via a mobile device, you password protect said device.<br/>
              <br/>
              You agree that any information you provide to us will be current, accurate and complete and that you will keep such information up to date by notifying us of any changes.<br/>
              <br/>
              We reserve the right to terminate any account at any time in our sole discretion, including without limitation for any failure to comply with these Terms of Use, any fraud or abuse, or any misrepresentation that you or anyone using your account may make to us.<br/>
              <br/>
              <strong className="font-bold">8. Profiles and Forums.</strong> You may be permitted to make available certain information or materials (each, a “<span className="underline">Submission</span>”) in connection with the Services, including on profile pages or interactive features. We have no control over and are not responsible for any Submissions, any use or misuse by any third party of Submissions or for your interactions with other users. Users are ultimately responsible for their own actions. If you choose to make your personal or other information publicly available through the Services, you do so at your own risk.<br/>
              <br/>
              You acknowledge that any forums contain the opinions and views of other users. You acknowledge further that we are not responsible for the accuracy of any Submissions on the Site. You understand and agree that all Submissions are the sole responsibility of the person who posted the Submission. You understand and agree that you will evaluate, and bear all risks associated with, the use of any Submission, including any reliance on the accuracy, completeness, or usefulness of such Submission.<br/>
              <br/>
              <strong className="font-bold">9. Our Right to Use Submissions.</strong> Nothing in this Agreement transfers any ownership rights in your Submissions. For each Submission, you grant to us a worldwide, royalty-free, fully paid-up, non-exclusive, perpetual, irrevocable, transferable and fully sublicensable (through multiple tiers) licence, without additional consideration to you or any third party, to reproduce, distribute, perform and display (publicly or otherwise), create derivative works of, adapt, modify, store and otherwise use, analyze and exploit such Submission, and to contact you about your Submission, in any format or media now known or hereafter developed, and for any purpose (including promotional purposes, such as testimonials and advertising).<br/>
              <br/>
              <strong className="font-bold">We are free to use any ideas, concepts, know-how, or techniques contained in or derived from any Submission for any purpose whatsoever, including developing, manufacturing, and marketing products. Therefore, please do not submit or send to us any ideas, suggestions or materials that you wish to keep confidential or for which you expect to receive compensation. You will not have any claim against us with respect to any use or non-use of Submissions,</strong> When you submit Submissions, you understand that we will have the right, but not the obligation, to use, display and publish your name, photograph, likeness, voice, performance, biographical information and/or statements, throughout the world in perpetuity on the Services and on any affiliate or successor site or social media channels owned or operated by us or our affiliates. If we make use of any of these rights, you understand and agree that you shall not receive any other consideration, payment, notification or credit, nor will you have any approval over how we use them.<br/>
              <br/>
              In addition, if you provide to us any ideas, proposals or suggestions (“<span className="underline">Feedback</span>”), we will deem such Feedback a Submission. You agree that Feedback is not confidential and that your provision of it is gratuitous, unsolicited and without restriction and does not place us under any obligation in respect of such Feedback.<br/>
              <br/>
              You confirm that (a) you have all rights necessary to grant the licences granted in this section, (b) your Submissions are complete and accurate, and (c) your Submissions and your provision of them to us are not fraudulent or otherwise in breach of any applicable law or any right of any third party. You further irrevocably waive (and consent to us performing any acts or omissions in relation to your Submissions and associated materials that may be inconsistent with) any “moral rights” or other rights with respect to attribution of authorship or integrity of materials regarding your Submission that you may have under any applicable law.<br/>
              <br/>
              We may impose a maximum amount of storage for Submissions on the Services. We are not responsible for any loss or harm you may suffer as a result of any deletion or failure to store any messages, communications or other Submission associated with maintaining the maximum amount of storage.<br/>
              <br/>
              <strong className="font-bold">10. Monitoring Use of the Service.</strong> We may (but have no obligation to) monitor, evaluate, alter or remove Submissions before or after they appear on the Services or analyze your access to or use of the Services. We may disclose information regarding your access to and use of the Services, the circumstances surrounding the transmission of Submissions, and personal information regarding users who make Submissions available, in each case in accordance with applicable law or a request by a court or law enforcement or other governmental authority, or otherwise in accordance with our Privacy Policy. <br/>
              <br/>
              <strong className="font-bold">11. Your Right to Use the Services.</strong> You acknowledge that all intellectual property rights in the Services, including the Site and the App, belong to us or our licensors. You have no right in or to the Services other than the right to access them in accordance with this Agreement. Subject to your compliance with, and solely for the duration of, this Agreement: (a) you may view one copy of the Site on any single device, solely for your personal, non-commercial use; (b) we permit you, on a limited, non-exclusive, revocable, non-transferable, non-sublicensable basis, to install and use the App on a device that you own or control, solely for your personal, non-commercial use. The App is licensed (not sold) to you. If you fail to comply with this Agreement, you must immediately cease using the Services, and delete the App from your device. You are responsible for keeping your device secure and protecting it appropriately.<br/>
              <br/>
              <strong className="font-bold">12. Company’s Proprietary Rights.</strong> We and our suppliers own the Services, which are protected by proprietary rights and laws, including all of our brand names, trademarks and service marks and any associated logos. All trade names, trademarks, service marks and logos (collectively, “<span className="underline">Marks</span>”) on the Services not owned by us are the property of their respective owners. You may not use our Marks in connection with any product or service that is not ours or in any manner that is likely to cause confusion. Nothing contained on the Services should be construed as granting any right to use any Marks without the express prior written consent of the owner.<br/>
              <br/>
              <strong className="font-bold">13. Third-Party Materials; Links.</strong> The Services may allow access to third-party information, products, services and other materials, including Submissions (collectively, “Third-Party Materials”), and including any access via links. We do not control or endorse, and are not responsible for, any <span className="underline">Third-Party Materials</span>. We have no obligation to monitor Third Party Materials, and we may block or disable access to any Third-Party Materials at any time. Your access or use of Third-Party Materials is at your own risk and is subject to any additional terms, conditions and policies applicable to such materials.<br/>
              <br/>
              <strong className="font-bold">14. Additional Terms.</strong> Additional terms may govern certain features or content of the Services, such as offers, prize draws, competitions, contests and sweepstakes. By participating in any activity as part of the Services governed by additional terms, such as a prize draw, competition, contest or sweepstakes with Official Rules, you agree that you will be subject to those additional terms in addition to these Terms of Use.<br/>
              <br/>
              <strong className="font-bold">15. DISCLAIMER OF WARRANTIES.</strong> TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW, THE SERVICES ARE MADE AVAILABLE TO YOU ON AN “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OR CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY.<br/>
              <br/>
              WE DISCLAIM ALL WARRANTIES WITH RESPECT TO THE SERVICES TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, INCLUDING THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT AND TITLE.<br/>
              <br/>
              TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, AND SUBJECT TO ANY APPLICABLE TERMS AND CONDITIONS OR POLICIES APPLICABLE TO THE USE OF THIRD-PARTY MATERIALS AS SET OUT IN SECTION 13, THIRD-PARTY MATERIALS ARE MADE AVAILABLE TO YOU ON AN “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES WITH RESPECT TO THIRD-PARTY MATERIALS. <br/>
              <br/>
              WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, WE MAKE NO REPRESENTATION OR WARRANTY THAT THE SERVICES WILL BE SECURE, THAT ANY USER NAME, PASSWORD OR OTHER SECURITY MEASURE THAT YOU MAY USE OR ALLOW OTHERS TO USE IN CONNECTION WITH THE SERVICES WILL PREVENT UNAUTHORIZED ACCESS TO YOUR SERVICES ACCOUNT OR RELATED INFORMATION, OR THAT YOUR SERVICES ACCOUNT OR RELATED INFORMATION WILL NOT BE ACCESSED OR MISUSED BY ANY THIRD PARTY.<br/>
              <br/>
              ALL DISCLAIMERS OF ANY KIND IN THIS AGREEMENT (INCLUDING IN THIS SECTION AND ELSEWHERE IN THIS AGREEMENT) ARE MADE FOR THE BENEFIT OF BOTH COMPANY AND ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, STOCKHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, REPRESENTATIVES, LICENSORS, SUPPLIERS AND SERVICE PROVIDERS, AND THEIR RESPECTIVE SUCCESSORS AND ASSIGNS (COLLECTIVELY, THE “COMPANY PARTIES”). <br/>
              <br/>
              While we take reasonable steps to try to maintain the timeliness, integrity and security of the Services, we cannot guarantee that they are or will remain updated, complete, correct or secure, or that access to them will be uninterrupted. The Services may include inaccuracies, errors and materials that conflict with this Agreement. Additionally, third parties may make unauthorized alterations to the Services. If you become aware of any such alteration, please use the Contact Us information below and provide a description of such alteration and its location on the Services.<br/>
              <br/>
              <strong className="font-bold">16. LIMITATION OF LIABILITY. </strong><br/>
              <br/>
              NOTHING IN THIS AGREEMENT RESTRICTS, EXCLUDES OR MODIFIES OR PURPORTS TO RESTRICT, EXCLUDE OR MODIFY ANY MANDATORY STATUTORY CONSUMER RIGHTS UNDER APPLICABLE LAW. <br/>
              <br/>
              WITH RESPECT TO ANY CONDITIONS, WARRANTIES OR GUARANTEES THAT CANNOT BE EXCLUDED UNDER APPLICABLE STATUTES, TO THE EXTENT PERMITTED BY APPLICABLE LAW, OUR LIABILITY IS LIMITED (AT OUR OPTION) TO THE RESUPPLY OR REFUND OF THE COST OF THE RELEVANT PORTION OF THE SERVICES. <br/>
              <br/>
              TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW: (A) WE WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY OR PUNITIVE DAMAGES OF ANY KIND, OR LOSSES THAT WERE NOT REASONABLY FORESEEABLE TO YOU OR US AT THE TIME YOU AGREED TO THIS AGREEMENT, IN EACH CASE ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR THIS AGREEMENT, AND UNDER ANY CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHER THEORY (COLLECTIVELY, “INDIRECT LOSSES”). LOSS OR DAMAGE IS FORESEEABLE IF EITHER IT IS OBVIOUS THAT IT WILL HAPPEN OR IF, AT THE TIME THE CONTRACT WAS MADE, BOTH YOU AND WE KNEW IT MIGHT HAPPEN.<br/>
              <br/>
              WITHOUT LIMITING THE FOREGOING, WE WILL NOT BE LIABLE FOR INDIRECT LOSSES OF ANY KIND RESULTING FROM YOUR USE OF OR INABILITY TO USE THE SERVICES OR FROM ANY PRODUCTS OR THIRD PARTY MATERIALS, INCLUDING FROM ANY VIRUS THAT MAY BE TRANSMITTED IN CONNECTION THEREWITH.<br/>
              <br/>
              THE COMPANY PARTIES DO NOT EXCLUDE OR LIMIT IN ANY WAY OUR LIABILITY TO YOU WHERE IT WOULD BE UNLAWFUL TO DO SO. THIS INCLUDES LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY OUR NEGLIGENCE OR THE NEGLIGENCE OF OUR EMPLOYEES, AGENTS OR SUBCONTRACTORS, FOR GROSS NEGLIGENCE OR WILLFUL BEHAVIOR, OR FOR FRAUD OR FRAUDULENT MISREPRESENTATION.<br/>
              <br/>          
              OUR MAXIMUM AGGREGATE LIABILITY FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR THIS AGREEMENT, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, WILL NOT EXCEED THE GREATER OF (A) THE TOTAL AMOUNT, IF ANY, PAID BY YOU TO US TO USE THE SERVICES; AND (B) TEN UNITED STATES DOLLARS ($10). <br/>
              <br/>
              ALL LIMITATIONS OF LIABILITY OF ANY KIND IN THIS AGREEMENT (INCLUDING IN THIS SECTION AND ELSEWHERE IN THIS AGREEMENT) ARE MADE FOR THE BENEFIT OF BOTH COMPANY AND THE COMPANY PARTIES. <br/>
              <br/>
              WITH RESPECT TO ANY CONDITIONS, WARRANTIES OR GUARANTEES THAT CANNOT BE EXCLUDED UNDER STATUTE, TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, OUR LIABILITY IS LIMITED (AT OUR OPTION) TO THE RESUPPLY OR REFUND OF THE COST OF RELEVANT SERVICES.<br/>
              <br/>
              <strong className="font-bold">17. Third Party Claims.</strong> If we are sued by a third party as a result of your breach of this Agreement or your infringement of any third-party right, then, to the fullest extent permitted by applicable law, you will be responsible for all liabilities, damages, judgments, awards, losses, costs, expenses and fees (including attorneys’ fees) incurred by the Company Parties.   <br/>
              <br/>
              <strong className="font-bold">18. Termination.</strong> You may stop using the Services, and thereby terminate this Agreement, at any time. We may terminate or suspend your use of the Services if you do not comply with this Agreement, engage in any fraud or abuse, or if you or anyone using your account makes any misrepresentation to us. Where reasonable under the circumstances, we will provide you with at least twenty-four (24) hours’ prior notice of termination or suspension, provided that, if we reasonably believe that you have materially breached this Agreement, we may immediately terminate or suspend you. Upon any termination or suspension, your right to use the Services will immediately cease, and we may, without liability to you or any third party, immediately deactivate or delete your user name, password and account, and all associated materials, without obligation to provide further access to such materials. Your obligations under this Agreement shall survive any expiration or termination of this Agreement. <br/>
              <br/>
              <strong className="font-bold">19. Governing Law; Jurisdiction.</strong> Unless otherwise prescribed by applicable law, this Agreement is governed by and shall be construed in accordance with the laws of the province of Ontario, without regard to its principles of conflicts of law, and regardless of your location. All disputes between you and us arising out of or related to the Services or this Agreement, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory and including non-contractual disputes or claims, shall be brought exclusively in a court of competent jurisdiction sitting in Ontario, and you agree to submit to the personal and exclusive jurisdiction of such courts.<br/>
              <br/>
              <strong className="font-bold">20. Filtering.</strong> Parental control protections (such as computer hardware, software or filtering services) are commercially available that may assist you in limiting access to material that may be harmful to or inappropriate for minors. Information identifying current providers of such protections (which we do not endorse) is available from <a href="https://en.wikipedia.org/wiki/Comparison_of_content-control_software_and_providers" target="_blank" rel="noreferrer" aria-label="Wikipedia page for Comparison of content control, software, and providers">https://en.wikipedia.org/wiki/<wbr/>Comparison_of_content-control_software_and_providers</a>. <br/>
              <br/>          
              <strong className="font-bold">21. Other Important Terms.</strong> This Agreement does not, and shall not be construed to, create any partnership, joint venture, employer-employee, agency or franchisor-franchisee relationship between you and us. This Agreement is between you and us. Except as set forth in Sections 17, 18 and 27, no other person shall have any rights to enforce any of the terms of this Agreement. If any provision of this Agreement is found to be unlawful, void or for any reason unenforceable, that provision will be deemed severable from this Agreement and will not affect the validity and enforceability of any remaining provision. You may not assign, transfer or sublicense any or all of your rights or obligations under this Agreement without our prior written consent. We may assign, transfer or sublicense any or all of our rights or obligations under this Agreement without restriction. No waiver by either party of any breach or default under this Agreement will be deemed to be a waiver of any preceding or subsequent breach or default. Any heading, caption or section title contained herein is for convenience only, and in no way defines or explains any section or provision. All terms defined in the singular shall have the same meanings when used in the plural, where appropriate and unless otherwise specified. Any use of the term “including” or variations thereof in this Agreement shall be construed as if followed by the phrase “without limitation.” This Agreement, including any terms and conditions incorporated herein, is the entire agreement between you and us relating to the subject matter of this Agreement, and, in the absence of fraud, supersedes any and all prior or contemporaneous written or oral agreements or understandings between you and us relating to such subject matter. Notices to you (including notices of changes to this Agreement) may be made via posting to the Services or by email (including in each case via links), or by regular mail. Without limitation, a printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. Neither party will be responsible for any failure to fulfill any obligation due to any cause beyond its control. <br/>
              <br/>
              <strong className="font-bold">22. Terms Required by Apple.</strong> In addition to your agreement with the foregoing terms and conditions, and notwithstanding anything to the contrary herein, the following provisions apply with respect to your use of any version of the App compatible with the iOS operating system of Apple Inc. (“<span className="underline">Apple</span>”). Apple is not a party to this Agreement and does not own and is not responsible for the App. Apple is not providing any warranty for the App except, if applicable, to refund the purchase price for it. Apple is not responsible for maintenance or other support services for the App and shall not be responsible for any other claims, losses, liabilities, damages, costs or expenses with respect to the App, including any third-party product liability claims, claims that the App fails to conform to any applicable legal or regulatory requirement, claims arising under consumer protection, privacy or similar legislation (including in connection with any use by the App of Apple’s HealthKit or HomeKit frameworks), and claims with respect to intellectual property infringement. Any inquiries or complaints relating to the use of the App, including those pertaining to intellectual property rights, must be directed to Company in accordance with the <span className="italics">“Information or Complaints”</span> section above. The license you have been granted herein is limited to a non-transferable license to use the App on an Apple-branded product that runs Apple’s iOS operating system and is owned or controlled by you, or as otherwise permitted by the Usage Rules set forth in Apple’s App Store Terms of Service, except that the App may be accessed and used by other accounts associated with the purchaser via Family Sharing or volume purchasing. In addition, you must comply with the terms of any third-party agreement applicable to you when using the App, such as your wireless data service agreement. Apple and Apple’s subsidiaries are third-party beneficiaries of this Agreement and, upon your acceptance of the terms and conditions of this Agreement, will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as a third-party beneficiary thereof; notwithstanding the foregoing, Company’s right to enter into, rescind or terminate any variation, waiver or settlement under this Agreement is not subject to the consent of any third party.<br/>
              <br/>
            </>,
            <>
              Vous êtes responsable de l’obtention, de l’entretien et du paiement de l’ensemble du matériel, des services de télécommunication et des autres services nécessaires pour l’utilisation des services.<br/>
              <br/>
              <strong className="font-bold">6. Communications électroniques.</strong> L’information communiquée dans le cadre des services peut constituer une communication électronique. Quand vous communiquez avec nous par l’intermédiaire des services ou d’autres voies électroniques, comme par courriel, vous communiquez avec nous de façon électronique. Vous convenez que nous pouvons communiquer avec vous par voie électronique, sous réserve du respect des lois locales antipourriel et des lois sur la protection des renseignements personnels, et que ces communications, de même que les avis, divulgations, ententes et autres communications électroniques, sont équivalentes aux communications par écrit et sont aussi valides que si elles étaient faites par écrit et signées par la partie qui les envoie.<br/>
              <br/>
              <strong className="font-bold">7. Inscription.</strong> Vous pourriez devoir vous inscrire pour utiliser les services. Nous pouvons refuser ou exiger que vous modifiiez tout nom d’utilisateur, mot de passe ou autre information que vous fournissez. Votre nom d’utilisateur et votre mot de passe sont réservés à votre usage personnel. Vous êtes seul responsable de préserver la confidentialité de vos identifiants et de restreindre l’accès à votre appareil mobile, à votre ordinateur et à tout autre moyen d’accéder aux services. Nous ne sommes pas responsables de toute utilisation de vos identifiants permise par le défaut d’en préserver la confidentialité. Vous êtes seul responsable de toutes les activités qui se produisent dans votre compte, à votre connaissance ou non. Vous devez nous informer rapidement de toute utilisation non autorisée de vos identifiants ou de votre compte dont vous prendriez connaissance. Si vous accédez aux services au moyen d’un appareil mobile, nous vous recommandons de protéger cet appareil par un mot de passe.<br/>
              <br/>
              Vous attestez que tous les renseignements que vous nous fournissez sont à jour, exacts et complets, et que vous gardez ces renseignements à jour en nous informant de tout changement.<br/>
              <br/>
              Nous nous réservons le droit de résilier tout compte à tout moment et à notre entière discrétion, par exemple en cas de violation des présentes conditions d’utilisation, de fraude ou d’abus, ou de toute fausse déclaration de votre part ou de la part de toute personne utilisant votre compte.<br/>
              <br/>
              <strong className="font-bold">8. Profils et forums.</strong> Vous pourriez être autorisé à rendre accessibles des renseignements ou du matériel (chacun, une {term("transmission")}) en lien avec les services, par exemple sur des pages de profil ou des fonctionnalités interactives. Nous n’avons aucun contrôle sur les transmissions, l’utilisation, abusive ou non, par un tiers des transmissions ou vos interactions avec d’autres utilisateurs, et ne sommes aucunement responsables de celles-ci. Les utilisateurs sont seuls responsables de leurs propres actions. Si vous choisissez de rendre vos renseignements personnels ou d’autres renseignements publiquement accessibles par l’intermédiaire des services, vous le faites à vos propres risques.<br/>
              <br/>
              Vous reconnaissez que tout forum contient des opinions et des points de vue d’autres utilisateurs. Vous reconnaissez en outre que nous ne sommes aucunement responsables de l’exactitude de toute transmission des utilisateurs. Vous comprenez et convenez que seule la personne à l’origine d’une transmission peut être tenue responsable de cette transmission. Vous comprenez et convenez que vous évaluerez et assumerez tous les risques de l’utilisation de toute transmission des utilisateurs, par exemple en vous fondant sur l’exactitude, l’exhaustivité ou l’utilité d’une transmission.<br/>
              <br/>
              <strong className="font-bold">9. Notre droit d’utiliser les transmissions.</strong> Aucune disposition de la présente entente ne transfère les droits de propriété de vos transmissions. Pour chaque transmission, vous nous accordez une licence mondiale, libre de redevances, entièrement libérée, non exclusive, perpétuelle, irrévocable, transférable et entièrement susceptible d’être concédée en sous-licence (par l’entremise de plusieurs niveaux) sans contrepartie supplémentaire pour vous ou un tiers, permettant de la reproduire, de la distribuer, de la présenter et de l’afficher (publiquement ou autrement), de créer des œuvres qui en sont dérivées, de l’adapter, de la modifier, de la stocker et de l’utiliser à d’autres fins, ainsi que de l’analyser et de l’exploiter, et de communiquer avec vous au sujet de votre transmission, dans tous les formats ou supports connus ou conçus à l’avenir et à quelque fin que ce soit (y compris à des fins promotionnelles, par exemple en tant que témoignage ou publicité).<br/>
              <br/>
              <strong className="font-bold">Nous pouvons librement utiliser les idées, les concepts, le savoir-faire ou les techniques qui se trouvent dans toute transmission des utilisateurs ou qui en sont tirés, et ce, à toutes fins, quelles qu’elles soient, y compris le développement, la fabrication et la commercialisation de produits. Par conséquent, veuillez éviter de nous soumettre ou de nous envoyer des idées, des suggestions ou des documents dont vous souhaitez préserver la confidentialité ou pour lesquels vous vous attendez à recevoir une rémunération. Vous ne pourrez réclamer quoi que ce soit de notre part relativement à l’utilisation ou à la non-utilisation des transmissions.</strong> Lorsque vous envoyez des transmissions, vous comprenez que nous aurons le droit, mais non l’obligation, d’utiliser, d’afficher et de publier votre nom, votre photographie, votre représentation, votre voix, votre performance, vos renseignements biographiques ou vos déclarations, partout dans le monde, dans les services et sur tout site ou toute chaîne des médias sociaux associés ou successeurs possédés et exploités par nous ou par nos filiales, et ce, à perpétuité. Si nous mettons en application l’un de ces droits, vous comprenez et convenez que vous ne recevrez pas de contrepartie, de paiement, de notification ou de crédit et que vous n’aurez pas à donner votre approbation sur la façon dont nous les utilisons.<br/>
              <br/>
              En outre, si vous nous fournissez des idées, des propositions ou des suggestions ({term("commentaires")}), nous considérerons ces commentaires comme une transmission. Vous convenez que les commentaires ne sont pas confidentiels et qu’ils sont gratuits, non sollicités et sans restriction, et qu’ils ne nous imposent aucune obligation à l’égard de ceux-ci.<br/>
              <br/>
              Vous confirmez a) que vous disposez de tous les droits nécessaires pour accorder les licences accordées en vertu de la présente section, b) que vos transmissions sont complètes et exactes et c) que vos transmissions et le fait que vous les rendiez accessibles ne constituent pas une fraude et n’enfreignent d’aucune manière les lois qui s’appliquent ou tout droit d’un tiers. En outre, vous renoncez irrévocablement à tout « droit moral » ou tout autre droit relatif à l’attribution de la paternité ou à l’intégrité du matériel en lien avec votre transmission que toute loi applicable pourrait vous conférer (et consentez à toute action ou omission de notre part en lien avec vos transmissions et le matériel associé qui pourraient être incompatibles avec ceux-ci).<br/>
              <br/>
              Nous pouvons imposer une quantité maximale d’espace de stockage pour les transmissions dans les services. Nous n’assumons aucune responsabilité relativement à la perte ou au préjudice que vous pourriez subir en raison de la suppression ou du défaut de stocker des messages, des communications ou d’autres transmissions en vue de respecter la quantité maximale d’espace de stockage.<br/>
              <br/>
              <strong className="font-bold">10. Surveillance de l’utilisation du service.</strong> Nous pouvons (sans en avoir l’obligation) surveiller, évaluer, modifier ou supprimer des transmissions avant ou après leur affichage dans les services ou analyser votre accès aux services ou votre utilisation de ceux-ci. Nous pourrions divulguer de l’information concernant votre accès aux services et leur utilisation et les circonstances de la mise à disposition des transmissions, et des renseignements personnels des utilisateurs qui rendent accessibles des transmissions, chaque fois conformément aux lois applicables ou à la demande d’un tribunal, d’une autorité judiciaire ou d’une autre autorité gouvernementale, ou conformément à notre politique de confidentialité. <br/>
              <br/>
              <strong className="font-bold">11. Votre droit d’utiliser les services.</strong> Vous reconnaissez que tous les droits de propriété intellectuelle sur les services, y compris le site et l’application, nous appartiennent ou appartiennent à nos concédants de licence. Vous n’avez aucun droit sur les services ni relativement à ceux-ci, à l’exception du droit d’y accéder conformément à la présente entente. Sous réserve de votre respect de la présente entente et uniquement pendant sa durée : a) vous pouvez afficher une copie du site sur tout appareil, uniquement pour votre usage personnel et non commercial; b) nous vous donnons l’autorisation limitée, non exclusive, révocable, non transférable, non susceptible d’être concédée en sous-licence, d’installer et d’utiliser l’application sur un appareil que vous possédez ou contrôlez, uniquement à des fins personnelles et non commerciales. Une licence d’utilisation de l’application vous est accordée (mais non vendue). Si vous contrevenez à la présente entente, vous devez immédiatement cesser d’utiliser les services et supprimer l’application de votre appareil. Vous avez la responsabilité de sécuriser et de protéger votre appareil.<br/>
              <br/>
              <strong className="font-bold">12. Droits de propriété de la société.</strong> Nous et nos fournisseurs sommes propriétaires des services, qui sont protégés par des droits de propriété et par la loi, lesquels comprennent tous nos noms de marque, marques de commerce et marques de service, ainsi que tous les logos qui y sont associés. Tous les noms commerciaux, marques de commerce, marques de service et logos (collectivement, les {term("marques")}) figurant dans les services qui ne nous appartiennent pas sont la propriété de leurs propriétaires respectifs. Vous n’êtes pas autorisé à utiliser nos marques en lien avec tout produit ou service qui n’est pas notre propriété ou d’une manière susceptible de causer de la confusion. Aucun élément des services ne doit être interprété comme l’octroi d’un droit d’utilisation de toute marque sans l’accord exprès préalable et par écrit du propriétaire.<br/>
              <br/>
              <strong className="font-bold">13. Matériel de tiers et liens.</strong> Les services peuvent donner accès à des renseignements, des produits, des services et d’autres documents de tiers, notamment des transmissions (collectivement, le {term("matériel de tiers")}), y compris l’accès au moyen de liens. Nous ne contrôlons et nous n’approuvons pas le matériel de tiers, et n’assumons aucune responsabilité à l’égard de celui-ci. Nous n’avons aucunement l’obligation de surveiller le matériel de tiers et nous pouvons bloquer ou désactiver l’accès au matériel de tiers à tout moment. Votre accès au matériel de tiers et son utilisation sont à vos propres risques et sont soumis à toutes les conditions d’utilisation et politiques supplémentaires qui s’appliquent à celui-ci.<br/>
              <br/>
              <strong className="font-bold">14. Conditions supplémentaires.</strong> Des conditions supplémentaires peuvent régir certaines fonctions ou certains contenus dans les services, comme des offres, des tirages de prix, des compétitions, des concours et des loteries promotionnelles. En participant à une activité offerte dans le cadre des services et régie par des conditions supplémentaires, comme le tirage d’un prix, une compétition, un concours ou une loterie promotionnelle soumis à un règlement officiel, vous acceptez d’être assujetti à ces conditions supplémentaires en plus des présentes conditions d’utilisation.<br/>
              <br/>
              <strong className="font-bold">15. ABSENCE DE GARANTIES.</strong> DANS LA PLEINE MESURE PERMISE PAR LA LOI APPLICABLE, LES SERVICES SONT MIS À VOTRE DISPOSITION EN L’ÉTAT, LÀ OÙ ILS SONT OFFERTS ET SELON LA DISPONIBILITÉ, SANS AUCUNE GARANTIE NI CONDITION DE QUELQUE NATURE QUE CE SOIT, EXPRESSE, IMPLICITE OU JURIDIQUE.<br/>
              <br/>
              NOUS DÉCLINONS TOUTES LES GARANTIES RELATIVES AUX SERVICES DANS LA PLEINE MESURE PERMISE PAR LA LOI APPLICABLE, Y COMPRIS LES GARANTIES DE QUALITÉ MARCHANDE, DE CONFORMITÉ À UN USAGE DONNÉ, D’ABSENCE DE CONTREFAÇON ET DE PROPRIÉTÉ.<br/>
              <br/>
              DANS LA PLEINE MESURE PERMISE PAR LES LOIS QUI S’APPLIQUENT ET SOUS RÉSERVE DES CONDITIONS D’UTILISATION OU DES POLITIQUES APPLICABLES À L’UTILISATION DE MATÉRIEL DE TIERS, ÉNONCÉES À LA SECTION 13, LE MATÉRIEL DE TIERS EST MIS À VOTRE DISPOSITION EN L’ÉTAT, LÀ OÙ IL EST OFFERT ET SELON LA DISPONIBILITÉ, SANS AUCUNE GARANTIE NI CONDITION DE QUELQUE NATURE QUE CE SOIT, EXPRESSE OU IMPLICITE. NOUS DÉCLINONS TOUTES LES GARANTIES RELATIVEMENT AU MATÉRIEL DE TIERS.<br/>
              <br/>
              SANS RESTREINDRE LA PORTÉE GÉNÉRALE DE CE QUI PRÉCÈDE ET DANS LA PLEINE MESURE PERMISE PAR LA LOI APPLICABLE, NOUS NE DÉCLARONS ET NE GARANTISSONS AUCUNEMENT QUE LES SERVICES SERONT SÉCURISÉS, QUE LES NOMS D’UTILISATEUR, MOTS DE PASSE ET MESURES DE SÉCURITÉ QUE VOUS POURRIEZ UTILISER OU AUTORISER D’AUTRES PERSONNES À UTILISER EN LIEN AVEC LES SERVICES PRÉVIENDRONT L’ACCÈS NON AUTORISÉ À VOTRE COMPTE DES SERVICES OU AUX DONNÉES QUI Y SONT ASSOCIÉES, OU QU’AUCUN TIERS N’AURA ACCÈS À VOTRE COMPTE DES SERVICES OU AUX DONNÉES QUI Y SONT ASSOCIÉES OU NE POURRA EN FAIRE UNE UTILISATION ABUSIVE.<br/>
              <br/>
              TOUTES LES EXONÉRATIONS DE RESPONSABILITÉ DE QUELQUE NATURE QUE CE SOIT DANS LA PRÉSENTE ENTENTE (DANS LA PRÉSENTE SECTION ET DANS LES AUTRES SECTIONS DE LA PRÉSENTE ENTENTE) SONT EN FAVEUR DE LA SOCIÉTÉ ET DE SES SOCIÉTÉS AFFILIÉES ET DE LEURS PARTIES PRENANTES, ACTIONNAIRES, ADMINISTRATEURS, DIRIGEANTS, EMPLOYÉS, AFFILIÉS, AGENTS, REPRÉSENTANTS, CONCÉDANTS DE LICENCE, FOURNISSEURS ET FOURNISSEURS DE SERVICES RESPECTIFS, AINSI QUE LEURS SUCCESSEURS ET AYANTS DROIT RESPECTIFS (COLLECTIVEMENT, LES {term("PARTIES PRENANTES DE LA SOCIÉTÉ")}).<br/>
              <br/>
              Bien que nous ayons pris des mesures raisonnables pour essayer de maintenir la rapidité, l’intégrité et la sécurité des services, nous ne pouvons garantir qu’ils sont ou resteront à jour, complets, corrects ou sécurisés, ou que l’accès aux services sera ininterrompu. Les services peuvent comprendre des inexactitudes, des erreurs et du matériel contrevenant à la présente entente. En outre, des tiers peuvent apporter des modifications non autorisées aux services. Si vous prenez connaissance d’une telle modification, veuillez communiquer avec nous aux coordonnées ci-dessous et nous fournir une description de cette modification et l’endroit où elle a été faite dans les services.<br/>
              <br/>
              <strong className="font-bold">16. LIMITATION DE RESPONSABILITÉ.</strong><br/>
              <br/>
              AUCUNE DISPOSITION DE LA PRÉSENTE ENTENTE NE RESTREINT, N’EXCLUT OU NE MODIFIE, NI NE PRÉTEND RESTREINDRE, EXCLURE OU MODIFIER, LES DROITS JURIDIQUES OBLIGATOIRES DES CONSOMMATEURS CONFÉRÉS PAR LA LOI APPLICABLE.<br/>
              <br/>
              QUANT AUX CONDITIONS OU GARANTIES QUI NE PEUVENT ÊTRE EXCLUES EN VERTU DES LOIS APPLICABLES, NOTRE RESPONSABILITÉ, DANS LA PLEINE MESURE PERMISE PAR CELLES-CI, SE LIMITE (À NOTRE DISCRÉTION) AU REMPLACEMENT OU AU REMBOURSEMENT DU COÛT DE LA PARTIE CONCERNÉE DES SERVICES.<br/>
              <br/>
              DANS LA PLEINE MESURE PERMISE PAR LA LOI APPLICABLE : A) NOUS NE POURRONS ÊTRE TENUS RESPONSABLES DES DOMMAGES INDIRECTS, ACCESSOIRES, CONSÉCUTIFS, SPÉCIAUX, EXEMPLAIRES OU PUNITIFS, DE QUELQUE NATURE QUE CE SOIT, OU DES PERTES QUE NI VOUS NI NOUS NE POUVONS RAISONNABLEMENT PRÉVOIR AU MOMENT OÙ VOUS ACCEPTEZ LA PRÉSENTE ENTENTE, DANS CHAQUE CAS DÉCOULANT DES SERVICES OU DE LA PRÉSENTE ENTENTE OU EN LIEN AVEC CEUX-CI, ET EN LIEN AVEC TOUT CONTRAT, DÉLIT (Y COMPRIS LA NÉGLIGENCE), RESPONSABILITÉ STRICTE OU AUTRE PRINCIPE DE DROIT (COLLECTIVEMENT, LES {term("PERTES INDIRECTES")}). LES PERTES OU LES DOMMAGES SONT PRÉVISIBLES S’IL EST ÉVIDENT QU’ILS SURVIENDRONT OU SI, AU MOMENT OÙ LE CONTRAT EST CONCLU, VOUS ET NOUS SAVONS QU’ILS POURRAIENT SURVENIR.<br/>
              <br/>
              SANS RESTREINDRE LA PORTÉE DE CE QUI PRÉCÈDE, NOUS NE POURRONS ÊTRE TENUS RESPONSABLES DE PERTES INDIRECTES DE TOUTE NATURE RÉSULTANT DE VOTRE UTILISATION OU DE L’IMPOSSIBILITÉ POUR VOUS D’UTILISER LES SERVICES OU DE TOUT PRODUIT OU MATÉRIEL DE TIERS, PAR EXEMPLE EN RAISON D’UN VIRUS POUVANT ÊTRE TRANSMIS PAR LEUR INTERMÉDIAIRE.<br/>
              <br/>
              LES PARTIES PRENANTES DE LA SOCIÉTÉ N’EXCLUENT OU NE RESTREIGNENT D’AUCUNE MANIÈRE NOTRE RESPONSABILITÉ DANS LES CAS OÙ IL SERAIT ILLÉGAL DE LE FAIRE. CELA COMPREND NOTRE RESPONSABILITÉ EN CAS DE DÉCÈS OU DE DOMMAGE CORPOREL DÉCOULANT DE NOTRE NÉGLIGENCE OU DE LA NÉGLIGENCE DE NOS EMPLOYÉS, AGENTS OU SOUS-TRAITANTS, D’UNE FAUTE LOURDE, D’UN ACTE DÉLIBÉRÉ, DE FRAUDE OU DE DÉCLARATION FALLACIEUSE.<br/>
              <br/>          
              NOTRE RESPONSABILITÉ GLOBALE MAXIMALE À L’ÉGARD DE TOUS LES DOMMAGES, PERTES ET CAUSES D’ACTION DÉCOULANT DES SERVICES OU DE LA PRÉSENTE ENTENTE, QU’ILS SOIENT CONTRACTUELS, DÉLICTUELS (Y COMPRIS LA NÉGLIGENCE) OU AUTRES, NE POURRA DÉPASSER LE PLUS ÉLEVÉ DES DEUX MONTANTS SUIVANTS : A) LE MONTANT TOTAL, LE CAS ÉCHÉANT, QUE VOUS NOUS AUREZ VERSÉ POUR UTILISER LES SERVICES, ET B) DIX DOLLARS (10 $) AMÉRICAINS.<br/>
              <br/>
              ALL LIMITATIONS OF LIABILITY OF ANY KIND IN THIS AGREEMENT (INCLUDING IN THIS SECTION AND ELSEWHERE IN THIS AGREEMENT) ARE MADE FOR THE BENEFIT OF BOTH COMPANY AND THE COMPANY PARTIES. <br/>
              <br/>
              TOUTES LES LIMITATIONS DE RESPONSABILITÉ, DE QUELQUE NATURE QUE CE SOIT, DANS LA PRÉSENTE ENTENTE (DANS LA PRÉSENTE SECTION ET DANS LES AUTRES SECTIONS DE LA PRÉSENTE ENTENTE) SONT EN FAVEUR DE LA SOCIÉTÉ ET DES PARTIES PRENANTES DE LA SOCIÉTÉ.<br/>
              <br/>
              QUANT AUX CONDITIONS OU GARANTIES QUI NE PEUVENT ÊTRE EXCLUES EN VERTU DES LOIS APPLICABLES, NOTRE RESPONSABILITÉ, DANS LA PLEINE MESURE PERMISE PAR CELLES-CI, SE LIMITE (À NOTRE DISCRÉTION) AU REMPLACEMENT OU AU REMBOURSEMENT DU COÛT DE LA PARTIE CONCERNÉE DES SERVICES.<br/>
              <br/>
              <strong className="font-bold">17. Réclamations de tiers.</strong> Si un tiers engage des poursuites contre nous à la suite d’une violation de la présente entente de votre part ou d’une violation de tout droit de tiers de votre part, vous assumerez l’entière responsabilité, dans la pleine mesure permise par la loi applicable, à l’égard des dommages, jugements, montants accordés, pertes, coûts, dépenses et frais (y compris les honoraires d’avocat) engagés par les parties prenantes de la société.<br/>
              <br/>
              <strong className="font-bold">18. Résiliation.</strong> Vous pouvez cesser d’utiliser les services et, par le fait même, mettre fin à la présente entente, à tout moment. Nous pouvons résilier ou suspendre votre droit d’utiliser les services si vous contrevenez à la présente entente, si vous prenez part à une fraude ou à un abus, ou si vous ou toute personne utilisant votre compte nous faites une fausse déclaration. Si les circonstances nous le permettent, nous vous informerons de la résiliation ou de la suspension au moins vingt-quatre (24) heures à l’avance, sauf si nous avons des motifs raisonnables de croire que vous avez substantiellement contrevenu à la présente entente, auquel cas nous pourrons mettre fin à votre utilisation ou la suspendre immédiatement. En cas de résiliation ou de suspension, votre droit d’utiliser les services vous sera immédiatement retiré et nous pourrons, sans responsabilité envers vous ou envers un tiers, désactiver ou supprimer immédiatement votre nom d’utilisateur, votre mot de passe et votre compte, ainsi que tout matériel qui y est associé, sans obligation de donner ensuite accès à ce matériel. Vos obligations en vertu de la présente entente seront maintenues à l’expiration ou à la résiliation de la présente entente.<br/>
              <br/>
              <strong className="font-bold">19. Lois applicables et compétence des tribunaux.</strong> Sauf disposition contraire dans la loi applicable, la présente entente est régie par les lois de l’Ontario et doit être interprétée en accord avec celles-ci, sans égard aux principes de conflits de lois de la province et de votre emplacement. Tous les différends entre vous et nous découlant des services ou de la présente entente, ou en lien avec ceux-ci, qu’ils soient fondés sur un contrat, un délit, une loi, une fraude, une fausse déclaration ou tout autre principe de droit, y compris les litiges ou réclamations non contractuels, seront exclusivement soumis à un tribunal compétent de l’Ontario, et vous acceptez de vous soumettre à la compétence personnelle et exclusive de ces tribunaux.<br/>
              <br/>
              <strong className="font-bold">20. Contrôle de l’accès.</strong> Du matériel informatique, des logiciels et des services de contrôle parental sont commercialisés et peuvent vous aider à restreindre l’accès à du matériel susceptible d’être préjudiciable ou inapproprié pour les mineurs. On trouve de l’information sur d’actuels fournisseurs de produits et services de contrôle parental (à l’égard desquels nous n’assumons aucune responsabilité) à l’adresse suivante&nbsp;: <a href="https://en.wikipedia.org/wiki/Comparison_of_content-control_software_and_providers" target="_blank" rel="noreferrer">https://en.wikipedia.org/wiki/<wbr/>Comparison_of_content-control_software_and_providers</a> (en anglais seulement).<br/>
              <br/>          
              <strong className="font-bold">21. Autres conditions importantes.</strong> La présente entente ne crée pas de partenariat, de coentreprise, d’agence ou de relation employeur-employé ou franchiseur-franchisé entre vous et nous, et ne doit pas être interprétée de telle façon. 
              La présente entente est conclue entre vous et nous. À l’exception des dispositions des sections 17, 18 et 27, aucune autre personne n’a l’autorisation de faire appliquer les conditions d’utilisation de la présente entente. 
              Si l’une des dispositions de la présente entente se révélait illégale, nulle ou pour quelque raison que ce soit inapplicable, cette disposition sera considérée comme dissociable de la présente entente et la validité et l’applicabilité des autres dispositions n’en seront pas affectées. 
              Vous n’êtes pas autorisé à céder, transférer ou concéder en sous-licence l’un ou l’ensemble de vos droits ou obligations en vertu de la présente entente sans avoir obtenu au préalable et par écrit notre consentement. Nous pouvons céder, transférer ou concéder en sous-licence l’un ou l’ensemble de nos droits ou obligations en vertu de la présente entente, et ce, sans restriction. 
              Aucune exonération de l’une ou l’autre des parties à l’égard d’une violation de la présente entente ou du défaut de s’y conformer ne sera pas considérée comme une exonération d’une violation ou d’un défaut antérieur ou ultérieur. 
              Tous les titres, sous-titres et titres de section de la présente entente ne sont donnés que pour des raisons pratiques et ne définissent ni n’expliquent d’aucune manière une section ou une disposition. 
              Tous les termes définis au singulier ont la même signification quand ils sont employés au pluriel, le cas échéant, sauf indication contraire. Tout emploi du terme « y compris », ainsi que ses variantes, dans la présente entente doit être interprété comme s’il était suivi de la formule « mais sans s’y limiter ». 
              La présente entente, y compris toutes les conditions d’utilisation qu’elle comporte, constitue l’intégralité de l’entente entre vous et nous concernant l’objet de la présente entente, et, sauf en cas de fraude, remplace toute entente écrite ou orale antérieure de la même période ou entre vous et nous en lien avec cet objet. Les avis qui vous sont destinés (y compris les avis de modifications de la présente entente) peuvent vous être transmis sous forme de publication dans les services ou par courriel (y compris dans chaque cas par l’intermédiaire de liens) ou par courrier postal. 
              Sans restriction, une version imprimée de la présente entente et de tout avis transmis par voie électronique sera recevable dans le cadre de procédures judiciaires ou administratives fondées sur la présente entente ou en lien avec celle-ci dans la même mesure et sous réserve des mêmes conditions que les autres dossiers commerciaux et documents d’archives initialement produits et conservés dans leur format imprimé. Aucune des parties ne sera responsable de tout manquement à ses obligations en raison d’une cause indépendante de sa volonté. <br/>
              <br/>
              <strong className="font-bold">22. Conditions requises par Apple.</strong> En plus de votre accord avec les modalités qui précèdent, et nonobstant toute disposition contraire aux présentes, les dispositions suivantes s’appliquent à votre utilisation de toute version de l’application compatible avec le système d’exploitation iOS d’Apple Inc. ({term("Apple")}). 
              Apple n’est pas partie à la présente entente et n’est pas propriétaire ni responsable de l’application Apple ne fournit aucune garantie pour l’application, sauf, le cas échéant, pour le remboursement du prix d’achat. 
              Apple n’est pas responsable de la maintenance ou d’autres services de soutien pour l’application et ne saurait être tenue responsable de tout autre réclamation, perte, responsabilité, dommage, coût ou dépense relativement à l’application, y compris toute réclamation de responsabilité civile liée à des produits tiers, toute réclamation selon laquelle l’application ne se conforme pas aux exigences légales ou réglementaires qui s’appliquent, toute réclamation découlant de toute loi sur la protection des consommateurs ou de la confidentialité ou d’une législation similaire (y compris en relation avec toute utilisation par l’application des cadres HealthKit ou HomeKit d’Apple) et toute réclamation relative à la violation de la propriété intellectuelle. Toute demande de renseignements ou plainte relative à l’utilisation de l’application, y compris celles relatives aux droits de propriété intellectuelle, doit être adressée à la société conformément à la section «&nbsp;<span className="italics">Demande de renseignements ou plaintes</span>&nbsp;» ci-dessus. La licence qui vous a été accordée aux présentes se limite à une licence non transférable d’utilisation de l’application sur un produit de marque Apple qui exécute le système d’exploitation iOS d’Apple et qui est détenu ou contrôlé par vous, ou comme le permettent les règles d’utilisation stipulées dans les Conditions d’utilisation de l’App Store d’Apple, sauf que l’application peut être accessible et utilisée par d’autres comptes associés à l’acheteur par l’entremise du partage familial ou de l’achat en volume. De plus, vous devez respecter les modalités de toute entente de tiers qui s’applique à vous lors de l’utilisation de l’application, tel que votre contrat de service de données sans fil. Apple et les filiales d’Apple sont des tiers bénéficiaires à la présente entente et, dès que vous aurez accepté les modalités de la présente entente, elles auront le droit (et seront réputées avoir accepté le droit) de faire appliquer la présente entente contre vous en tant que tiers bénéficiaire; nonobstant ce qui précède, le droit de la société de conclure, d’annuler ou de mettre fin à toute modification, renonciation ou tout règlement en vertu de la présente entente n’est pas sujet au consentement de toute tierce partie.<br/>
              <br/>
            </>,
          )}
        </p>
      </article>
    </main>
  )
}