import ChevronHeader from "./materials/ChevronHeader";

import "../styles/TermsOfUse.scss";

export default function TermsOfUse({ modal }) {
  // ensure page is scrolled to top upon mount
  window.scrollTo(0,0);

  return (
    <main className={`nav-shadow ${modal ? "blur" : ""}`}>
      <ChevronHeader
        bgLeft={'bg-header-orange'}
        text={<>Terms of Use</>}
        bgRight={'bg-header-red'}
      />
      <article className="terms">
        <h2 className="font-orange font-bold">TERMS OF SERVICE</h2>
        <p>
          Last Updated: April 29, 2019<br/>
          <br/>
          Please read these Terms of Service (the “<span className="underline">Agreement</span>”) carefully. By clicking or tapping “OK” or “Agree” (or a similar term) in connection with this Agreement, or by using the Services (as defined below), you agree to this Agreement. We recommend that you print a copy of this Agreement for future reference. We retain the right to make changes, as outlined below.<br/>
          This Agreement is between you and Janssen Inc. (“<span className="underline">Company</span>” or “<span className="underline">we</span>” or “<span className="underline">us</span>” or “<span className="underline">our</span>”) concerning your use of the Dosing Conversion Guides site located at invegasustennahcp.ca (the “<span className="underline">Site</span>”) the mobile software application in connection with which you are accessing this Agreement (the “<span className="underline">App</span>” or the “<span className="underline">Services</span>”).<br/>
          <br/>
          If you are not willing to accept the terms and conditions in the Agreement, we ask that you not access or use the Services or post or submit any materials on it or order any items from it. Please review our Privacy Policy located at <a href="http://www.janssen.com/canada/privacy" target="_blank" rel="noreferrer">http://www.janssen.com/canada/privacy</a> for details about what information we collect and how we use it.<br/>
          <br/>
          THIS SITE IS INTENDED FOR AND DIRECTED TO RESIDENTS OF CANADA. YOU AFFIRM THAT YOU ARE OF LEGAL AGE TO ENTER INTO THIS AGREEMENT.<br/>
          IF YOU ARE USING THE SERVICES ON BEHALF OF, OR FOR THE BENEFIT OF, ANY ORGANIZATION WITH WHICH YOU ARE ASSOCIATED, THEN YOU AGREE TO THE TERMS OF THIS AGREEMENT ON BEHALF OF YOURSELF AND SUCH ORGANIZATION, AND YOU CONFIRM THAT YOU HAVE THE LEGAL AUTHORITY TO BIND SUCH ORGANIZATION TO THIS AGREEMENT.<br/>
          References to “you” and “your” in this Agreement will refer to both you and any such organization.<br/>
          <br/>
          <strong className="font-bold">1. Our Right to Make Changes.</strong> We may change this Agreement from time to time (for any reason, such as changes in the functions or services offered by this Site or to reflect a change in the law) by notifying you of such changes by any reasonable means and by making available a revised Agreement through the Services. Any such changes will not apply to any dispute between you and us arising prior to the date on which we posted the revised Agreement incorporating such changes or otherwise notified you of such changes. Your clicking or tapping “OK” or “Agree” (or a similar term) in connection with this Agreement or your use of the Services following any changes will constitute your acceptance of such changes. The “Last Updated” legend above indicates when this Agreement was last changed.<br/>
          To the extent permitted by applicable law, we may, at any time and without liability, modify or discontinue all or part of the Services (e.g., to reflect changes in the relevant laws, to protect the security of the Services or to implement reasonable technical adjustments and improvements, to modify the services and functions provided by the Site); charge, modify or waive any fees required to use the Services where reasonably necessary; or offer opportunities to some or all users, at our sole discretion. We will seek to notify you by reasonable means of (i) any modifications that will have a material adverse effect on your use of the Services, taken as a whole; and (ii) any material increase in the fees charged by us to use the Services.<br/>
          <br/>
          <strong className="font-bold">2. Information Disclaimer.</strong> THE INFORMATION INCLUDING ANY, ADVICE AND RECOMMENDATIONS PROVIDED AS PART OF THE SERVICES IS INTENDED SOLELY FOR EDUCATIONAL AND INFORMATIONAL PURPOSES. IT IS NOT INTENDED AS MEDICAL OR HEALTHCARE ADVICE, OR TO BE USED FOR MEDICAL DIAGNOSIS OR TREATMENT, FOR ANY INDIVIDUAL PROBLEM. IT IS ALSO NOT INTENDED AS A SUBSTITUTE FOR PROFESSIONAL ADVICE AND SERVICES FROM A QUALIFIED HEALTHCARE PROVIDER FAMILIAR WITH YOUR UNIQUE FACTS. ALWAYS SEEK THE ADVICE OF YOUR DOCTOR OR OTHER QUALIFIED HEALTHCARE PROVIDER REGARDING ANY MEDICAL CONDITION AND BEFORE STARTING ANY NEW TREATMENT. YOUR USE OF THE SERVICES IS SUBJECT TO THE ADDITIONAL DISCLAIMERS AND CAVEATS THAT MAY APPEAR THROUGHOUT THE SERVICES.<br/>
          <br/>
          WE ASSUME NO RESPONSIBILITY FOR ANY CONSEQUENCE RELATING DIRECTLY OR INDIRECTLY TO ANY ACTION OR INACTION YOU TAKE BASED ON THE INFORMATION, OR OTHER MATERIAL PROVIDED AS PART OF THE SERVICES. WHILE WE STRIVE TO KEEP THE INFORMATION PROVIDED BY THE SERVICES TO BE ACCURATE, COMPLETE, AND UP TO DATE, WE DO NOT GIVE ANY ASSURANCES AND WILL NOT BE RESPONSIBLE FOR ANY DAMAGE OR LOSS RELATED TO THE ACCURACY, COMPLETENESS, OR TIMELINESS OF THE INFORMATION PROVIDED AS PART OF THE SERVICES.<br/>
          <br/>
          <strong className="font-bold">3. Information Submitted Through the Services.</strong> Your submission of information through the Services is governed by our Privacy Policy.<br/>
          <br/>
          <strong className="font-bold">4. Jurisdictional Issues.</strong> The Services may not be appropriate or available for use in some jurisdictions. Any use of the Services is at your own risk, and you must comply with all applicable laws, rules and regulations in doing so. We may limit the availability of the Services at any time, in whole or in part, to any person or geographic area that we choose, in our sole discretion, for valid reasons (e.g., to comply with relevant laws and regulatory requirements, to protect the security of the Services or to implement reasonable technical adjustments).<br/>
          <br/>
          <strong className="font-bold">5. Acceptable Use and Rules of Conduct.</strong> You must not:
        </p>
        <ul className="terms-bullet-list">
          <li><span>Post, transmit or otherwise make available through or in connection with the Services any materials that are or may be: (a) threatening, harassing, degrading, hateful, intimidating, or otherwise fail to respect the rights and dignity of others; (b) defamatory, libelous or fraudulent; (c) obscene, indecent, pornographic or otherwise objectionable; or (d) protected by copyright, trademark, trade secret, right of publicity or privacy or any other proprietary right, without the express prior written consent of the applicable owner.</span></li>
          <li><span>Post, transmit or otherwise make available through or in connection with the Services any virus, worm, Trojan horse, Easter egg, time bomb, spyware or other computer code, file or program that is or is potentially harmful or invasive or intended to damage or hijack the operation of, or to monitor the use of, any hardware, software or equipment (each, a “Virus”).</span></li>
          <li><span>Use the Services for any commercial purpose, including use for your commercial purposes or any commercial purposes that will benefit you in any way.</span></li>
          <li><span>Use the Services for any purpose that is fraudulent or otherwise unlawful.</span></li>
          <li><span>Collect information about users of the Services in any way, including through reverse engineering.</span></li>
          <li><span>Interfere with the operation of the Services or the servers or networks used to make the Services available, including by hacking or defacing any portion of the Services, or violate any requirement or policy of such servers or networks.</span></li>
          <li><span>Restrict or inhibit any other person from using the Services.</span></li>
          <li><span>Reproduce, modify, adapt, translate, create derivative works of, sell, rent, lease, loan, timeshare, distribute or otherwise exploit any portion of (or any use of) the Services except as expressly authorized under this Agreement, without our express prior written consent.</span></li>
          <li><span>Reverse engineer, decompile or disassemble any portion of the Services, except where such restriction is expressly prohibited by applicable law.</span></li>
          <li><span>Remove any copyright, trademark or other proprietary rights notice from the Services.</span></li>
          <li><span>Incorporate any portion of the Services into any product or service, without our express prior written consent.</span></li>
          <li><span>Systematically download and store Services content.</span></li>
          <li><span>Use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or otherwise gather Services content, or reproduce or circumvent the navigational structure or presentation of the Services, without our express prior written consent. Notwithstanding the foregoing, and subject to compliance with any instructions posted in the robots.txt file located in the root directory of the Services, we grant to the operators of public search engines permission to use spiders to copy materials from the Services for the sole purpose of (and solely to the extent necessary for) creating publicly available, searchable indices of such materials, but not caches or archives of such materials. We reserve the right to revoke such permission either generally or in specific cases, at any time and without notice. </span></li>
        </ul>
        <p>
          You are responsible for obtaining, maintaining and paying for all hardware, telecommunications and other services needed for you to use the Services.<br/>
          <br/>
          <strong className="font-bold">6. Electronic Communications.</strong>The information communicated as part of the Services may constitute an electronic communication. When you communicate with us through the Services or via other forms of electronic media, such as e-mail, you are communicating with us electronically. You agree that we may communicate electronically, subject to local privacy and Anti-Spam laws, and that such communications, as well as notices, disclosures, agreements, and other communications that we provide to you electronically, are equivalent to communications in writing and shall have the same force and effect as if they were in writing and signed by the party sending the communication.<br/>
          <br/>
          <strong className="font-bold">7. Registration.</strong> You may need to register to use the Services. We may reject, or require that you change, any user name, password or other information that you provide. Your user name and password are for your personal use only. You are solely responsible for maintaining the confidentiality of your credentials and for restricting access to your mobile device, computer, and/or other means of accessing the Services. We are not responsible for any use of your credentials caused by your failure to keep them confidential. You are solely responsible for all activities that occur under your account, either with or without your knowledge. You must promptly notify us of any unauthorized use of your credentials or account of which you become aware. We recommend that, to the extent you access the Services via a mobile device, you password protect said device.<br/>
          <br/>
          You agree that any information you provide to us will be current, accurate and complete and that you will keep such information up to date by notifying us of any changes.<br/>
          <br/>
          We reserve the right to terminate any account at any time in our sole discretion, including without limitation for any failure to comply with these Terms of Use, any fraud or abuse, or any misrepresentation that you or anyone using your account may make to us.<br/>
          <br/>
          <strong className="font-bold">8. Profiles and Forums.</strong> You may be permitted to make available certain information or materials (each, a “Submission”) in connection with the Services, including on profile pages or interactive features. We have no control over and are not responsible for any Submissions, any use or misuse by any third party of Submissions or for your interactions with other users. Users are ultimately responsible for their own actions. If you choose to make your personal or other information publicly available through the Services, you do so at your own risk.<br/>
          <br/>
          You acknowledge that any forums contain the opinions and views of other users. You acknowledge further that we are not responsible for the accuracy of any Submissions on the Site. You understand and agree that all Submissions are the sole responsibility of the person who posted the Submission. You understand and agree that you will evaluate, and bear all risks associated with, the use of any Submission, including any reliance on the accuracy, completeness, or usefulness of such Submission.<br/>
          <br/>
          <strong className="font-bold">9. Our Right to Use Submissions.</strong> Nothing in this Agreement transfers any ownership rights in your Submissions. For each Submission, you grant to us a worldwide, royalty-free, fully paid-up, non-exclusive, perpetual, irrevocable, transferable and fully sublicensable (through multiple tiers) licence, without additional consideration to you or any third party, to reproduce, distribute, perform and display (publicly or otherwise), create derivative works of, adapt, modify, store and otherwise use, analyze and exploit such Submission, and to contact you about your Submission, in any format or media now known or hereafter developed, and for any purpose (including promotional purposes, such as testimonials and advertising).<br/>
          <br/>
          <strong className="font-bold">We are free to use any ideas, concepts, know-how, or techniques contained in or derived from any Submission for any purpose whatsoever, including developing, manufacturing, and marketing products. Therefore, please do not submit or send to us any ideas, suggestions or materials that you wish to keep confidential or for which you expect to receive compensation. You will not have any claim against us with respect to any use or non-use of Submissions,</strong> When you submit Submissions, you understand that we will have the right, but not the obligation, to use, display and publish your name, photograph, likeness, voice, performance, biographical information and/or statements, throughout the world in perpetuity on the Services and on any affiliate or successor site or social media channels owned or operated by us or our affiliates. If we make use of any of these rights, you understand and agree that you shall not receive any other consideration, payment, notification or credit, nor will you have any approval over how we use them.<br/>
          <br/>
          In addition, if you provide to us any ideas, proposals or suggestions (“<span className="underline">Feedback</span>”), we will deem such Feedback a Submission. You agree that Feedback is not confidential and that your provision of it is gratuitous, unsolicited and without restriction and does not place us under any obligation in respect of such Feedback.<br/>
          <br/>
          You confirm that (a) you have all rights necessary to grant the licences granted in this section, (b) your Submissions are complete and accurate, and (c) your Submissions and your provision of them to us are not fraudulent or otherwise in breach of any applicable law or any right of any third party. You further irrevocably waive (and consent to us performing any acts or omissions in relation to your Submissions and associated materials that may be inconsistent with) any “moral rights” or other rights with respect to attribution of authorship or integrity of materials regarding your Submission that you may have under any applicable law.<br/>
          <br/>
          We may impose a maximum amount of storage for Submissions on the Services. We are not responsible for any loss or harm you may suffer as a result of any deletion or failure to store any messages, communications or other Submission associated with maintaining the maximum amount of storage.<br/>
          <br/>
          <strong className="font-bold">10. Monitoring Use of the Service.</strong> We may (but have no obligation to) monitor, evaluate, alter or remove Submissions before or after they appear on the Services or analyze your access to or use of the Services. We may disclose information regarding your access to and use of the Services, the circumstances surrounding the transmission of Submissions, and personal information regarding users who make Submissions available, in each case in accordance with applicable law or a request by a court or law enforcement or other governmental authority, or otherwise in accordance with our Privacy Policy. <br/>
          <br/>
          <strong className="font-bold">11. Your Right to Use the Services.</strong> You acknowledge that all intellectual property rights in the Services, including the Site and the App, belong to us or our licensors. You have no right in or to the Services other than the right to access them in accordance with this Agreement. Subject to your compliance with, and solely for the duration of, this Agreement: (a) you may view one copy of the Site on any single device, solely for your personal, non-commercial use; (b) we permit you, on a limited, non-exclusive, revocable, non-transferable, non-sublicensable basis, to install and use the App on a device that you own or control, solely for your personal, non-commercial use. The App is licensed (not sold) to you. If you fail to comply with this Agreement, you must immediately cease using the Services, and delete the App from your device. You are responsible for keeping your device secure and protecting it appropriately.<br/>
          <br/>
          <strong className="font-bold">12. Company’s Proprietary Rights.</strong> We and our suppliers own the Services, which are protected by proprietary rights and laws, including all of our brand names, trademarks and service marks and any associated logos. All trade names, trademarks, service marks and logos (collectively, “<span className="underline">Marks</span>”) on the Services not owned by us are the property of their respective owners. You may not use our Marks in connection with any product or service that is not ours or in any manner that is likely to cause confusion. Nothing contained on the Services should be construed as granting any right to use any Marks without the express prior written consent of the owner.<br/>
          <br/>
          <strong className="font-bold">13. Third-Party Materials; Links.</strong> The Services may allow access to third-party information, products, services and other materials, including Submissions (collectively, “Third-Party Materials”), and including any access via links. We do not control or endorse, and are not responsible for, any <span className="underline">Third-Party Materials</span>. We have no obligation to monitor Third Party Materials, and we may block or disable access to any Third-Party Materials at any time. Your access or use of Third-Party Materials is at your own risk and is subject to any additional terms, conditions and policies applicable to such materials.<br/>
          <br/>
          <strong className="font-bold">14. Additional Terms.</strong> Additional terms may govern certain features or content of the Services, such as offers, prize draws, competitions, contests and sweepstakes. By participating in any activity as part of the Services governed by additional terms, such as a prize draw, competition, contest or sweepstakes with Official Rules, you agree that you will be subject to those additional terms in addition to these Terms of Use.<br/>
          <br/>
          <strong className="font-bold">15. DISCLAIMER OF WARRANTIES.</strong> TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW, THE SERVICES ARE MADE AVAILABLE TO YOU ON AN “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OR CONDITIONS OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY.<br/>
          <br/>
           WE DISCLAIM ALL WARRANTIES WITH RESPECT TO THE SERVICES TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, INCLUDING THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT AND TITLE.<br/>
          <br/>
           TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, AND SUBJECT TO ANY APPLICABLE TERMS AND CONDITIONS OR POLICIES APPLICABLE TO THE USE OF THIRD-PARTY MATERIALS AS SET OUT IN SECTION 13, THIRD-PARTY MATERIALS ARE MADE AVAILABLE TO YOU ON AN “AS IS,” “WHERE IS” AND “WHERE AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED. WE DISCLAIM ALL WARRANTIES WITH RESPECT TO THIRD-PARTY MATERIALS. <br/>
          <br/>
           WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, WE MAKE NO REPRESENTATION OR WARRANTY THAT THE SERVICES WILL BE SECURE, THAT ANY USER NAME, PASSWORD OR OTHER SECURITY MEASURE THAT YOU MAY USE OR ALLOW OTHERS TO USE IN CONNECTION WITH THE SERVICES WILL PREVENT UNAUTHORIZED ACCESS TO YOUR SERVICES ACCOUNT OR RELATED INFORMATION, OR THAT YOUR SERVICES ACCOUNT OR RELATED INFORMATION WILL NOT BE ACCESSED OR MISUSED BY ANY THIRD PARTY.<br/>
          <br/>
           ALL DISCLAIMERS OF ANY KIND IN THIS AGREEMENT (INCLUDING IN THIS SECTION AND ELSEWHERE IN THIS AGREEMENT) ARE MADE FOR THE BENEFIT OF BOTH COMPANY AND ITS AFFILIATES AND THEIR RESPECTIVE SHAREHOLDERS, STOCKHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES, AFFILIATES, AGENTS, REPRESENTATIVES, LICENSORS, SUPPLIERS AND SERVICE PROVIDERS, AND THEIR RESPECTIVE SUCCESSORS AND ASSIGNS (COLLECTIVELY, THE “COMPANY PARTIES”). <br/>
          <br/>
           While we take reasonable steps to try to maintain the timeliness, integrity and security of the Services, we cannot guarantee that they are or will remain updated, complete, correct or secure, or that access to them will be uninterrupted. The Services may include inaccuracies, errors and materials that conflict with this Agreement. Additionally, third parties may make unauthorized alterations to the Services. If you become aware of any such alteration, please use the Contact Us information below and provide a description of such alteration and its location on the Services.<br/>
          <br/>
          <strong className="font-bold">16. LIMITATION OF LIABILITY. </strong><br/>
          <br/>
           NOTHING IN THIS AGREEMENT RESTRICTS, EXCLUDES OR MODIFIES OR PURPORTS TO RESTRICT, EXCLUDE OR MODIFY ANY MANDATORY STATUTORY CONSUMER RIGHTS UNDER APPLICABLE LAW. <br/>
          <br/>
           WITH RESPECT TO ANY CONDITIONS, WARRANTIES OR GUARANTEES THAT CANNOT BE EXCLUDED UNDER APPLICABLE STATUTES, TO THE EXTENT PERMITTED BY APPLICABLE LAW, OUR LIABILITY IS LIMITED (AT OUR OPTION) TO THE RESUPPLY OR REFUND OF THE COST OF THE RELEVANT PORTION OF THE SERVICES. <br/>
          <br/>
           TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW: (A) WE WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, EXEMPLARY OR PUNITIVE DAMAGES OF ANY KIND, OR LOSSES THAT WERE NOT REASONABLY FORESEEABLE TO YOU OR US AT THE TIME YOU AGREED TO THIS AGREEMENT, IN EACH CASE ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR THIS AGREEMENT, AND UNDER ANY CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHER THEORY (COLLECTIVELY, “INDIRECT LOSSES”). LOSS OR DAMAGE IS FORESEEABLE IF EITHER IT IS OBVIOUS THAT IT WILL HAPPEN OR IF, AT THE TIME THE CONTRACT WAS MADE, BOTH YOU AND WE KNEW IT MIGHT HAPPEN.<br/>
          <br/>
           WITHOUT LIMITING THE FOREGOING, WE WILL NOT BE LIABLE FOR INDIRECT LOSSES OF ANY KIND RESULTING FROM YOUR USE OF OR INABILITY TO USE THE SERVICES OR FROM ANY PRODUCTS OR THIRD PARTY MATERIALS, INCLUDING FROM ANY VIRUS THAT MAY BE TRANSMITTED IN CONNECTION THEREWITH.<br/>
          <br/>
           THE COMPANY PARTIES DO NOT EXCLUDE OR LIMIT IN ANY WAY OUR LIABILITY TO YOU WHERE IT WOULD BE UNLAWFUL TO DO SO. THIS INCLUDES LIABILITY FOR DEATH OR PERSONAL INJURY CAUSED BY OUR NEGLIGENCE OR THE NEGLIGENCE OF OUR EMPLOYEES, AGENTS OR SUBCONTRACTORS, FOR GROSS NEGLIGENCE OR WILLFUL BEHAVIOR, OR FOR FRAUD OR FRAUDULENT MISREPRESENTATION.<br/>
          <br/>          
           OUR MAXIMUM AGGREGATE LIABILITY FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR THIS AGREEMENT, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, WILL NOT EXCEED THE GREATER OF (A) THE TOTAL AMOUNT, IF ANY, PAID BY YOU TO US TO USE THE SERVICES; AND (B) TEN UNITED STATES DOLLARS ($10). <br/>
          <br/>
           ALL LIMITATIONS OF LIABILITY OF ANY KIND IN THIS AGREEMENT (INCLUDING IN THIS SECTION AND ELSEWHERE IN THIS AGREEMENT) ARE MADE FOR THE BENEFIT OF BOTH COMPANY AND THE COMPANY PARTIES. <br/>
          <br/>
           WITH RESPECT TO ANY CONDITIONS, WARRANTIES OR GUARANTEES THAT CANNOT BE EXCLUDED UNDER STATUTE, TO THE EXTENT PERMITTED UNDER APPLICABLE LAW, OUR LIABILITY IS LIMITED (AT OUR OPTION) TO THE RESUPPLY OR REFUND OF THE COST OF RELEVANT SERVICES.<br/>
          <br/>
          <strong className="font-bold">17. Third Party Claims.</strong> If we are sued by a third party as a result of your breach of this Agreement or your infringement of any third-party right, then, to the fullest extent permitted by applicable law, you will be responsible for all liabilities, damages, judgments, awards, losses, costs, expenses and fees (including attorneys’ fees) incurred by the Company Parties.   <br/>
          <br/>
          <strong className="font-bold">18. Termination.</strong> You may stop using the Services, and thereby terminate this Agreement, at any time. We may terminate or suspend your use of the Services if you do not comply with this Agreement, engage in any fraud or abuse, or if you or anyone using your account makes any misrepresentation to us. Where reasonable under the circumstances, we will provide you with at least twenty-four (24) hours’ prior notice of termination or suspension, provided that, if we reasonably believe that you have materially breached this Agreement, we may immediately terminate or suspend you. Upon any termination or suspension, your right to use the Services will immediately cease, and we may, without liability to you or any third party, immediately deactivate or delete your user name, password and account, and all associated materials, without obligation to provide further access to such materials. Your obligations under this Agreement shall survive any expiration or termination of this Agreement. <br/>
          <br/>
          <strong className="font-bold">19. Governing Law; Jurisdiction.</strong> Unless otherwise prescribed by applicable law, this Agreement is governed by and shall be construed in accordance with the laws of the province of Ontario, without regard to its principles of conflicts of law, and regardless of your location. All disputes between you and us arising out of or related to the Services or this Agreement, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory and including non-contractual disputes or claims, shall be brought exclusively in a court of competent jurisdiction sitting in Ontario, and you agree to submit to the personal and exclusive jurisdiction of such courts.<br/>
          <br/>
          <strong className="font-bold">20. Filtering.</strong> Parental control protections (such as computer hardware, software or filtering services) are commercially available that may assist you in limiting access to material that may be harmful to or inappropriate for minors. Information identifying current providers of such protections (which we do not endorse) is available from <a href="https://en.wikipedia.org/wiki/Comparison_of_content-control_software_and_providers" target="_blank" rel="noreferrer">https://en.wikipedia.org/wiki/<wbr/>Comparison_of_content-control_software_and_providers</a>. <br/>
          <br/>          
          <strong className="font-bold">21. Other Important Terms.</strong> This Agreement does not, and shall not be construed to, create any partnership, joint venture, employer-employee, agency or franchisor-franchisee relationship between you and us. This Agreement is between you and us. Except as set forth in Sections 17, 18 and 27, no other person shall have any rights to enforce any of the terms of this Agreement. If any provision of this Agreement is found to be unlawful, void or for any reason unenforceable, that provision will be deemed severable from this Agreement and will not affect the validity and enforceability of any remaining provision. You may not assign, transfer or sublicense any or all of your rights or obligations under this Agreement without our prior written consent. We may assign, transfer or sublicense any or all of our rights or obligations under this Agreement without restriction. No waiver by either party of any breach or default under this Agreement will be deemed to be a waiver of any preceding or subsequent breach or default. Any heading, caption or section title contained herein is for convenience only, and in no way defines or explains any section or provision. All terms defined in the singular shall have the same meanings when used in the plural, where appropriate and unless otherwise specified. Any use of the term “including” or variations thereof in this Agreement shall be construed as if followed by the phrase “without limitation.” This Agreement, including any terms and conditions incorporated herein, is the entire agreement between you and us relating to the subject matter of this Agreement, and, in the absence of fraud, supersedes any and all prior or contemporaneous written or oral agreements or understandings between you and us relating to such subject matter. Notices to you (including notices of changes to this Agreement) may be made via posting to the Services or by e-mail (including in each case via links), or by regular mail. Without limitation, a printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. Neither party will be responsible for any failure to fulfill any obligation due to any cause beyond its control. <br/>
          <br/>
          <strong className="font-bold">22. Terms Required by Apple.</strong> In addition to your agreement with the foregoing terms and conditions, and notwithstanding anything to the contrary herein, the following provisions apply with respect to your use of any version of the App compatible with the iOS operating system of Apple Inc. (“<span className="underline">Apple</span>”). Apple is not a party to this Agreement and does not own and is not responsible for the App. Apple is not providing any warranty for the App except, if applicable, to refund the purchase price for it. Apple is not responsible for maintenance or other support services for the App and shall not be responsible for any other claims, losses, liabilities, damages, costs or expenses with respect to the App, including any third-party product liability claims, claims that the App fails to conform to any applicable legal or regulatory requirement, claims arising under consumer protection, privacy or similar legislation (including in connection with any use by the App of Apple’s HealthKit or HomeKit frameworks), and claims with respect to intellectual property infringement. Any inquiries or complaints relating to the use of the App, including those pertaining to intellectual property rights, must be directed to Company in accordance with the “Information or Complaints” section above. The license you have been granted herein is limited to a non-transferable license to use the App on an Apple-branded product that runs Apple’s iOS operating system and is owned or controlled by you, or as otherwise permitted by the Usage Rules set forth in Apple’s App Store Terms of Service, except that the App may be accessed and used by other accounts associated with the purchaser via Family Sharing or volume purchasing. In addition, you must comply with the terms of any third-party agreement applicable to you when using the App, such as your wireless data service agreement. Apple and Apple’s subsidiaries are third-party beneficiaries of this Agreement and, upon your acceptance of the terms and conditions of this Agreement, will have the right (and will be deemed to have accepted the right) to enforce this Agreement against you as a third-party beneficiary thereof; notwithstanding the foregoing, Company’s right to enter into, rescind or terminate any variation, waiver or settlement under this Agreement is not subject to the consent of any third party.<br/>
          <br/>
        </p>
      </article>
    </main>
  )
}